import { ExpenseCategory, IncomeType, CurrencyCode, CurrencyConfig } from '../types/budget';

export interface CategoryMeta {
  name: ExpenseCategory;
  color: string;
  bgColor: string;
  borderColor: string;
  chartColor: string;
  iconName: string;
  ruleType: 'Needs' | 'Wants' | 'Savings';
  description: string;
}

export const EXPENSE_CATEGORIES_META: Record<string, CategoryMeta> = {
  Food: {
    name: 'Food',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    chartColor: '#f59e0b',
    iconName: 'Utensils',
    ruleType: 'Needs',
    description: 'Groceries, dining, snacks & takeout',
  },
  'Food & Dining': {
    name: 'Food & Dining',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    chartColor: '#f59e0b',
    iconName: 'Utensils',
    ruleType: 'Needs',
    description: 'Groceries, dining, snacks & takeout',
  },
  Transport: {
    name: 'Transport',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    chartColor: '#06b6d4',
    iconName: 'Car',
    ruleType: 'Needs',
    description: 'Fuel, transit, cabs, parking & maintenance',
  },
  Transportation: {
    name: 'Transportation',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    chartColor: '#06b6d4',
    iconName: 'Car',
    ruleType: 'Needs',
    description: 'Fuel, transit, cabs, parking & maintenance',
  },
  Shopping: {
    name: 'Shopping',
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    chartColor: '#a855f7',
    iconName: 'ShoppingBag',
    ruleType: 'Wants',
    description: 'Clothing, electronics, apparel & retail',
  },
  Rent: {
    name: 'Rent',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    chartColor: '#3b82f6',
    iconName: 'Home',
    ruleType: 'Needs',
    description: 'Monthly apartment & property rent',
  },
  Electricity: {
    name: 'Electricity',
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/30',
    chartColor: '#eab308',
    iconName: 'Zap',
    ruleType: 'Needs',
    description: 'Power grid & electricity utility bill',
  },
  Water: {
    name: 'Water',
    color: 'text-sky-400',
    bgColor: 'bg-sky-500/10',
    borderColor: 'border-sky-500/30',
    chartColor: '#38bdf8',
    iconName: 'Droplet',
    ruleType: 'Needs',
    description: 'Water utility & supply bill',
  },
  Internet: {
    name: 'Internet',
    color: 'text-indigo-400',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    chartColor: '#6366f1',
    iconName: 'Wifi',
    ruleType: 'Needs',
    description: 'Broadband, fiber & mobile data',
  },
  'Housing & Utilities': {
    name: 'Housing & Utilities',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    chartColor: '#3b82f6',
    iconName: 'Home',
    ruleType: 'Needs',
    description: 'Housing rent, maintenance & utilities',
  },
  Education: {
    name: 'Education',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    chartColor: '#10b981',
    iconName: 'GraduationCap',
    ruleType: 'Needs',
    description: 'Tuition fees, courses & books',
  },
  'Education & Books': {
    name: 'Education & Books',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    chartColor: '#10b981',
    iconName: 'GraduationCap',
    ruleType: 'Needs',
    description: 'Tuition fees, courses & books',
  },
  Healthcare: {
    name: 'Healthcare',
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/30',
    chartColor: '#f43f5e',
    iconName: 'HeartPulse',
    ruleType: 'Needs',
    description: 'Medical checkups, pharmacy & insurance',
  },
  'Health & Wellness': {
    name: 'Health & Wellness',
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/30',
    chartColor: '#f43f5e',
    iconName: 'HeartPulse',
    ruleType: 'Needs',
    description: 'Medical checkups, pharmacy & insurance',
  },
  Entertainment: {
    name: 'Entertainment',
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    chartColor: '#ec4899',
    iconName: 'Film',
    ruleType: 'Wants',
    description: 'Movies, streaming, gaming & outings',
  },
  'Entertainment & Fun': {
    name: 'Entertainment & Fun',
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    chartColor: '#ec4899',
    iconName: 'Film',
    ruleType: 'Wants',
    description: 'Movies, streaming, gaming & outings',
  },
  Travel: {
    name: 'Travel',
    color: 'text-teal-400',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    chartColor: '#14b8a6',
    iconName: 'Plane',
    ruleType: 'Wants',
    description: 'Vacation trips, flights & hotels',
  },
  Insurance: {
    name: 'Insurance',
    color: 'text-slate-400',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-500/30',
    chartColor: '#64748b',
    iconName: 'Shield',
    ruleType: 'Needs',
    description: 'Health, life & vehicle insurance premiums',
  },
  'EMI/Loan': {
    name: 'EMI/Loan',
    color: 'text-orange-400',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    chartColor: '#f97316',
    iconName: 'CreditCard',
    ruleType: 'Needs',
    description: 'Home loan, car loan & personal EMIs',
  },
  'Investments & Savings': {
    name: 'Investments & Savings',
    color: 'text-indigo-400',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    chartColor: '#6366f1',
    iconName: 'TrendingUp',
    ruleType: 'Savings',
    description: 'Stocks, mutual funds & deposits',
  },
  'Personal Care': {
    name: 'Personal Care',
    color: 'text-teal-400',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    chartColor: '#14b8a6',
    iconName: 'Sparkles',
    ruleType: 'Wants',
    description: 'Grooming, salon & skincare',
  },
  Miscellaneous: {
    name: 'Miscellaneous',
    color: 'text-slate-400',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-500/30',
    chartColor: '#64748b',
    iconName: 'MoreHorizontal',
    ruleType: 'Wants',
    description: 'Uncategorized one-off expenses',
  },
  Other: {
    name: 'Other',
    color: 'text-slate-400',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-500/30',
    chartColor: '#64748b',
    iconName: 'MoreHorizontal',
    ruleType: 'Wants',
    description: 'Other misc expenses',
  },
};

export const EXPENSE_CATEGORIES: ExpenseCategory[] = Object.keys(EXPENSE_CATEGORIES_META) as ExpenseCategory[];


export const INCOME_SOURCES: IncomeType[] = [
  'Salary',
  'Freelance',
  'Business',
  'Investment',
  'Bonus',
  'Interest',
  'Gift',
  'Other',
  'Salary / Wages',
  'Freelance / Projects',
  'Investments & Dividends',
  'Part-time Work',
  'Allowance & Stipend',
  'Side Hustle',
  'Gifts & Rewards',
];

export const CURRENCIES: Record<CurrencyCode, CurrencyConfig> = {
  INR: { code: 'INR', symbol: '₹', label: 'Indian Rupee (INR ₹)', rateToUSD: 0.012 },
  USD: { code: 'USD', symbol: '$', label: 'US Dollar (USD $)', rateToUSD: 1.0 },
  EUR: { code: 'EUR', symbol: '€', label: 'Euro (EUR €)', rateToUSD: 1.08 },
  GBP: { code: 'GBP', symbol: '£', label: 'British Pound (GBP £)', rateToUSD: 1.28 },
  CAD: { code: 'CAD', symbol: 'C$', label: 'Canadian Dollar (CAD C$)', rateToUSD: 0.74 },
  AUD: { code: 'AUD', symbol: 'A$', label: 'Australian Dollar (AUD A$)', rateToUSD: 0.66 },
  JPY: { code: 'JPY', symbol: '¥', label: 'Japanese Yen (JPY ¥)', rateToUSD: 0.0067 },
};

export function formatMoney(amount: number, currency: CurrencyCode = 'INR'): string {
  const cfg = CURRENCIES[currency] || CURRENCIES.INR;
  return `${cfg.symbol}${amount.toLocaleString(undefined, {
    minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
    maximumFractionDigits: 2,
  })}`;
}
