import { UserProfile, ExpenseItem, IncomeItem, BudgetLimit, PersonTransfer, PaymentCard, SavingsGoal } from '../types/budget';

export const DEMO_USERS: Record<string, UserProfile> = {
  'user_admin_primary': {
    id: 'user_admin_primary',
    email: 'skarthick2804@gmail.com',
    fullName: 'Karthik Admin',
    name: 'Karthik Admin',
    role: 'admin',
    accountStatus: 'active',
    monthlyIncomeGoal: 80000,
    currency: 'INR',
    savingsTargetPercent: 30,
    is_verified: true,
    premiumStatus: 'ACTIVE',
    premiumPlan: 'YEARLY',
    premiumStartedAt: '2026-08-01T00:00:00.000Z',
    premiumExpiresAt: '2027-08-01T00:00:00.000Z',
  },
  'user_1': {
    id: 'user_1',
    email: 'skarthik874@gmail.com',
    fullName: 'Karthik',
    name: 'Karthik',
    role: 'super_admin',
    accountStatus: 'active',
    monthlyIncomeGoal: 50000,
    currency: 'INR',
    savingsTargetPercent: 30,
    is_verified: true,
    premiumStatus: 'ACTIVE',
    premiumPlan: 'YEARLY',
    premiumStartedAt: '2026-08-01T00:00:00.000Z',
    premiumExpiresAt: '2027-08-01T00:00:00.000Z',
  },
  'user_2': {
    id: 'user_2',
    email: 'alex.freelancer@budgetvault.io',
    fullName: 'Alex Morgan',
    name: 'Alex Morgan',
    role: 'freelancer',
    accountStatus: 'active',
    monthlyIncomeGoal: 75000,
    currency: 'USD',
    savingsTargetPercent: 25,
    is_verified: true,
    premiumStatus: 'ACTIVE',
    premiumPlan: 'MONTHLY',
    premiumStartedAt: '2026-08-20T00:00:00.000Z',
    premiumExpiresAt: '2026-09-20T00:00:00.000Z',
  },
  'user_3': {
    id: 'user_3',
    email: 'david.student@university.edu',
    fullName: 'David Kim',
    name: 'David Kim',
    role: 'student',
    accountStatus: 'active',
    monthlyIncomeGoal: 20000,
    currency: 'INR',
    savingsTargetPercent: 15,
    is_verified: true,
    premiumStatus: 'NONE',
    premiumPlan: 'FREE',
  },
  'user_4': {
    id: 'user_4',
    email: 'household.admin@family.org',
    fullName: 'Elena & Family',
    name: 'Elena & Family',
    role: 'admin',
    accountStatus: 'active',
    monthlyIncomeGoal: 120000,
    currency: 'EUR',
    savingsTargetPercent: 35,
    is_verified: true,
    premiumStatus: 'ACTIVE',
    premiumPlan: 'YEARLY',
    premiumStartedAt: '2026-07-01T00:00:00.000Z',
    premiumExpiresAt: '2027-07-01T00:00:00.000Z',
  },
};

export const INITIAL_USER: UserProfile = DEMO_USERS['user_1'];

// Current month helper
const now = new Date();
const currentYear = now.getFullYear();
const currentMonthStr = String(now.getMonth() + 1).padStart(2, '0');
const currentMonthYear = `${currentYear}-${currentMonthStr}`;

export const INITIAL_BUDGETS: BudgetLimit[] = [
  {
    id: 'b_1',
    userId: 'user_1',
    category: 'Food & Dining',
    monthlyLimit: 9000,
    monthYear: currentMonthYear,
    alertThresholdPercent: 80,
  },
  {
    id: 'b_2',
    userId: 'user_1',
    category: 'Housing & Utilities',
    monthlyLimit: 14000,
    monthYear: currentMonthYear,
    alertThresholdPercent: 85,
  },
  {
    id: 'b_3',
    userId: 'user_1',
    category: 'Transportation',
    monthlyLimit: 4000,
    monthYear: currentMonthYear,
    alertThresholdPercent: 80,
  },
  {
    id: 'b_4',
    userId: 'user_1',
    category: 'Education & Books',
    monthlyLimit: 5000,
    monthYear: currentMonthYear,
    alertThresholdPercent: 80,
  },
  {
    id: 'b_5',
    userId: 'user_1',
    category: 'Shopping',
    monthlyLimit: 4500,
    monthYear: currentMonthYear,
    alertThresholdPercent: 75,
  },
  {
    id: 'b_6',
    userId: 'user_1',
    category: 'Entertainment & Fun',
    monthlyLimit: 3000,
    monthYear: currentMonthYear,
    alertThresholdPercent: 75,
  },
  {
    id: 'b_7',
    userId: 'user_1',
    category: 'Health & Wellness',
    monthlyLimit: 2500,
    monthYear: currentMonthYear,
    alertThresholdPercent: 80,
  },
  {
    id: 'b_8',
    userId: 'user_1',
    category: 'Investments & Savings',
    monthlyLimit: 8000,
    monthYear: currentMonthYear,
    alertThresholdPercent: 90,
  },
];

export const INITIAL_INCOMES: IncomeItem[] = [
  {
    id: 'inc_1',
    userId: 'user_1',
    source: 'Salary / Wages',
    amount: 38000,
    description: 'Monthly professional salary credited',
    date: `${currentMonthYear}-01`,
    isRecurring: true,
    notes: 'Direct bank transfer credited on 1st',
    createdAt: new Date(`${currentMonthYear}-01T09:00:00Z`).toISOString(),
  },
  {
    id: 'inc_2',
    userId: 'user_1',
    source: 'Freelance / Projects',
    amount: 14500,
    description: 'Frontend dashboard design milestone',
    date: `${currentMonthYear}-08`,
    isRecurring: false,
    notes: 'Milestone 2 payment received via UPI',
    createdAt: new Date(`${currentMonthYear}-08T14:30:00Z`).toISOString(),
  },
  {
    id: 'inc_3',
    userId: 'user_1',
    source: 'Investments & Dividends',
    amount: 2400,
    description: 'Quarterly mutual fund return payout',
    date: `${currentMonthYear}-12`,
    isRecurring: false,
    notes: 'Auto credited to savings',
    createdAt: new Date(`${currentMonthYear}-12T11:15:00Z`).toISOString(),
  },
];

export const INITIAL_EXPENSES: ExpenseItem[] = [
  {
    id: 'exp_1',
    userId: 'user_1',
    category: 'Housing & Utilities',
    amount: 12000,
    description: 'Apartment rent & maintenance',
    date: `${currentMonthYear}-02`,
    paymentMethod: 'Bank Transfer',
    notes: 'Paid to landlord directly',
    createdAt: new Date(`${currentMonthYear}-02T10:00:00Z`).toISOString(),
  },
  {
    id: 'exp_2',
    userId: 'user_1',
    category: 'Housing & Utilities',
    amount: 1150,
    description: 'High-speed Wi-Fi fiber plan',
    date: `${currentMonthYear}-03`,
    paymentMethod: 'UPI / Card',
    notes: 'Airtel Broadband monthly bill',
    createdAt: new Date(`${currentMonthYear}-03T11:00:00Z`).toISOString(),
  },
  {
    id: 'exp_3',
    userId: 'user_1',
    category: 'Food & Dining',
    amount: 3450,
    description: 'Supermarket monthly staples & groceries',
    date: `${currentMonthYear}-04`,
    paymentMethod: 'UPI / Card',
    notes: 'BigBasket delivery with fruits and grains',
    createdAt: new Date(`${currentMonthYear}-04T16:20:00Z`).toISOString(),
  },
  {
    id: 'exp_4',
    userId: 'user_1',
    category: 'Transportation',
    amount: 1200,
    description: 'Monthly Metro SmartCard recharge',
    date: `${currentMonthYear}-05`,
    paymentMethod: 'UPI / Card',
    notes: 'Commute recharge',
    createdAt: new Date(`${currentMonthYear}-05T09:15:00Z`).toISOString(),
  },
  {
    id: 'exp_5',
    userId: 'user_1',
    category: 'Education & Books',
    amount: 2400,
    description: 'System Architecture & Design book bundle',
    date: `${currentMonthYear}-07`,
    paymentMethod: 'UPI / Card',
    notes: 'Study reference books',
    createdAt: new Date(`${currentMonthYear}-07T13:40:00Z`).toISOString(),
  },
  {
    id: 'exp_6',
    userId: 'user_1',
    category: 'Food & Dining',
    amount: 1250,
    description: 'Weekend dinner with team mates',
    date: `${currentMonthYear}-09`,
    paymentMethod: 'UPI / Card',
    notes: 'Italian bistro dining split',
    createdAt: new Date(`${currentMonthYear}-09T20:30:00Z`).toISOString(),
  },
  {
    id: 'exp_7',
    userId: 'user_1',
    category: 'Shopping',
    amount: 1999,
    description: 'Ergonomic workstation accessories',
    date: `${currentMonthYear}-11`,
    paymentMethod: 'Credit Card',
    notes: 'Desk setup upgrade',
    createdAt: new Date(`${currentMonthYear}-11T15:10:00Z`).toISOString(),
  },
  {
    id: 'exp_8',
    userId: 'user_1',
    category: 'Entertainment & Fun',
    amount: 799,
    description: 'Streaming & cloud music subscription',
    date: `${currentMonthYear}-12`,
    paymentMethod: 'UPI / Card',
    notes: 'Auto-renewed subscription',
    createdAt: new Date(`${currentMonthYear}-12T08:00:00Z`).toISOString(),
  },
  {
    id: 'exp_9',
    userId: 'user_1',
    category: 'Health & Wellness',
    amount: 1500,
    description: 'Monthly gym & fitness pass',
    date: `${currentMonthYear}-14`,
    paymentMethod: 'UPI / Card',
    notes: 'Cult fitness membership pass',
    createdAt: new Date(`${currentMonthYear}-14T07:30:00Z`).toISOString(),
  },
  {
    id: 'exp_10',
    userId: 'user_1',
    category: 'Investments & Savings',
    amount: 6000,
    description: 'Systematic Investment Plan (SIP)',
    date: `${currentMonthYear}-15`,
    paymentMethod: 'Bank Transfer',
    notes: 'Index fund auto debit',
    createdAt: new Date(`${currentMonthYear}-15T09:00:00Z`).toISOString(),
  },
];

// Personal Tracking Machine: Transfers, Peer Charges, Send & Received Money
export const INITIAL_TRANSFERS: PersonTransfer[] = [
  {
    id: 'tr_101',
    userId: 'user_1',
    personName: 'Rohan Sharma',
    type: 'received',
    amount: 3200,
    category: 'Rent & Utility Share',
    date: `${currentMonthYear}-03`,
    status: 'completed',
    paymentMode: 'UPI',
    referenceNote: 'Rohan sent his half of high-speed Wi-Fi and apartment maintenance',
    createdAt: new Date(`${currentMonthYear}-03T12:00:00Z`).toISOString(),
  },
  {
    id: 'tr_102',
    userId: 'user_1',
    personName: 'Priya Patel',
    type: 'sent',
    amount: 1450,
    category: 'Dinner & Cab Split',
    date: `${currentMonthYear}-06`,
    status: 'completed',
    paymentMode: 'UPI',
    referenceNote: 'Sent reimbursement for team dinner & late cab',
    createdAt: new Date(`${currentMonthYear}-06T21:40:00Z`).toISOString(),
  },
  {
    id: 'tr_103',
    userId: 'user_1',
    personName: 'Vikram Mehta',
    type: 'charged',
    amount: 2500,
    category: 'Event Tickets Booking',
    date: `${currentMonthYear}-09`,
    status: 'pending',
    paymentMode: 'UPI',
    referenceNote: 'Charged Vikram for tech conference group pass booked on card',
    createdAt: new Date(`${currentMonthYear}-09T15:10:00Z`).toISOString(),
  },
  {
    id: 'tr_104',
    userId: 'user_1',
    personName: 'Ananya Roy',
    type: 'received',
    amount: 5000,
    category: 'Freelance Collaboration',
    date: `${currentMonthYear}-11`,
    status: 'completed',
    paymentMode: 'Bank Transfer',
    referenceNote: 'Payment share received for joint UI research module',
    createdAt: new Date(`${currentMonthYear}-11T16:30:00Z`).toISOString(),
  },
  {
    id: 'tr_105',
    userId: 'user_1',
    personName: 'Siddharth Nair',
    type: 'split',
    amount: 850,
    category: 'Grocery Bulk Order',
    date: `${currentMonthYear}-13`,
    status: 'settled',
    paymentMode: 'UPI',
    referenceNote: 'Settled split order share for weekend cooking supplies',
    createdAt: new Date(`${currentMonthYear}-13T18:00:00Z`).toISOString(),
  },
  {
    id: 'tr_106',
    userId: 'user_1',
    personName: 'Kavita Singh',
    type: 'charged',
    amount: 1200,
    category: 'Subscription Family Plan',
    date: `${currentMonthYear}-14`,
    status: 'pending',
    paymentMode: 'Digital Wallet',
    referenceNote: 'Annual streaming cloud family slot fee requested',
    createdAt: new Date(`${currentMonthYear}-14T11:00:00Z`).toISOString(),
  },
];

// Payment Cards & Bank Accounts
export const INITIAL_CARDS: PaymentCard[] = [
  {
    id: 'card_1',
    userId: 'user_1',
    cardName: 'Millennia Platinum',
    bankName: 'HDFC Bank',
    cardType: 'credit',
    last4: '4829',
    balanceOrDue: 8750,
    creditLimit: 150000,
    expiryMonthYear: '08/28',
    isFrozen: false,
    colorTheme: 'obsidian',
    billingDay: 20,
    network: 'Visa',
  },
  {
    id: 'card_2',
    userId: 'user_1',
    cardName: 'Salary Advantage Account',
    bankName: 'ICICI Bank',
    cardType: 'debit',
    last4: '9103',
    balanceOrDue: 64200,
    creditLimit: 0,
    expiryMonthYear: '11/29',
    isFrozen: false,
    colorTheme: 'sapphire',
    billingDay: 1,
    network: 'Mastercard',
  },
  {
    id: 'card_3',
    userId: 'user_1',
    cardName: 'Sapphire Preferred',
    bankName: 'Chase Bank',
    cardType: 'credit',
    last4: '3318',
    balanceOrDue: 2400,
    creditLimit: 75000,
    expiryMonthYear: '04/27',
    isFrozen: false,
    colorTheme: 'indigo',
    billingDay: 15,
    network: 'Visa',
  },
  {
    id: 'card_4',
    userId: 'user_1',
    cardName: 'Emergency High-Yield Savings',
    bankName: 'State Bank of India',
    cardType: 'bank_account',
    last4: '7740',
    balanceOrDue: 185000,
    creditLimit: 0,
    expiryMonthYear: '12/32',
    isFrozen: false,
    colorTheme: 'emerald',
    network: 'RuPay',
  },
];

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'sg_1',
    userId: 'user_1',
    title: '6-Month Emergency Vault',
    targetAmount: 300000,
    currentAmount: 185000,
    category: 'Emergency',
    targetDate: '2026-12-31',
    colorTheme: 'emerald',
    notes: 'Safe liquid reserve stored in High-Yield account.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sg_2',
    userId: 'user_1',
    title: 'Electric Vehicle Fund',
    targetAmount: 500000,
    currentAmount: 220000,
    category: 'Vehicle',
    targetDate: '2027-06-30',
    colorTheme: 'cyan',
    notes: 'Saving for downpayment on Tesla / Tata EV.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sg_3',
    userId: 'user_1',
    title: 'Japan Autumn Trip',
    targetAmount: 150000,
    currentAmount: 95000,
    category: 'Vacation',
    targetDate: '2026-10-15',
    colorTheme: 'indigo',
    notes: 'Flights, stay, and local experience budget.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sg_4',
    userId: 'user_1',
    title: 'MacBook Pro M4 Max',
    targetAmount: 250000,
    currentAmount: 160000,
    category: 'Gadget',
    targetDate: '2026-11-20',
    colorTheme: 'sunset',
    notes: 'Primary workstation upgrade fund.',
    createdAt: new Date().toISOString(),
  },
];
