"""accounts table updation creating

Revision ID: 050d36c4fe3e
Revises: 0e05c2ecd1de
Create Date: 2026-08-09 01:37:28.270231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050d36c4fe3e'
down_revision: Union[str, Sequence[str], None] = '0e05c2ecd1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_goals_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    op.add_column('accounts', sa.Column('bank_name', sa.String(length=50), nullable=False))
    op.add_column('accounts', sa.Column('account_number', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['account_number'])
    op.drop_column('accounts', 'account_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'account_number')
    op.drop_column('accounts', 'bank_name')
    op.create_table('savings_goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('savings_goals_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('savings_goals_pkey'))
    )
    op.create_index(op.f('ix_savings_goals_id'), 'savings_goals', ['id'], unique=False)
    # ### end Alembic commands ###
