"""account field in expense

Revision ID: 1ad3ccabac85
Revises: 325f9bd07991
Create Date: 2026-08-06 19:58:58.260672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad3ccabac85'
down_revision: Union[str, Sequence[str], None] = '325f9bd07991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('account', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'account')
    # ### end Alembic commands ###
