"""accounts indexed on user_id

Revision ID: 256c7ef77251
Revises: 050d36c4fe3e
Create Date: 2026-08-09 02:00:18.517877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256c7ef77251'
down_revision: Union[str, Sequence[str], None] = '050d36c4fe3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    # ### end Alembic commands ###
