"""create subscription_requests table

Revision ID: 2f1e0d2691eb
Revises: e588c3525040
Create Date: 2026-09-01 19:34:15.311719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1e0d2691eb'
down_revision: Union[str, Sequence[str], None] = 'e588c3525040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_requests_id'), 'subscription_requests', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_requests_status'), 'subscription_requests', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_requests_user_id'), 'subscription_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_requests_user_id'), table_name='subscription_requests')
    op.drop_index(op.f('ix_subscription_requests_status'), table_name='subscription_requests')
    op.drop_index(op.f('ix_subscription_requests_id'), table_name='subscription_requests')
    op.drop_table('subscription_requests')
    # ### end Alembic commands ###
