"""account field in income

Revision ID: 325f9bd07991
Revises: 8905844bd2a2
Create Date: 2026-08-05 19:49:26.375911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325f9bd07991'
down_revision: Union[str, Sequence[str], None] = '8905844bd2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('account', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'account')
    # ### end Alembic commands ###
