"""scoped_account_number_uniqueness

Revision ID: adf5574238d4
Revises: 2f1e0d2691eb
Create Date: 2026-09-01 20:18:43.781650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf5574238d4'
down_revision: Union[str, Sequence[str], None] = '2f1e0d2691eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_account_number_key'), 'accounts', type_='unique')
    op.create_unique_constraint('uq_user_bank_account', 'accounts', ['user_id', 'bank_name', 'account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_bank_account', 'accounts', type_='unique')
    op.create_unique_constraint(op.f('accounts_account_number_key'), 'accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
