"""income, expenses and saving schemas

Revision ID: bf86c54f0420
Revises: 30ba3c8ce4e6
Create Date: 2026-07-24 22:26:47.156219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf86c54f0420'
down_revision: Union[str, Sequence[str], None] = '30ba3c8ce4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('budgets', sa.Column('monthly_limit', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.drop_constraint(op.f('budgets_user_id_fkey'), 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('expenses', sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('expenses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('expenses_user_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('incomes', sa.Column('source', sa.String(length=100), nullable=False))
    op.add_column('incomes', sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('incomes', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('incomes_user_id_fkey'), 'incomes', type_='foreignkey')
    op.create_foreign_key(None, 'incomes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.create_foreign_key(op.f('incomes_user_id_fkey'), 'incomes', 'users', ['user_id'], ['id'])
    op.drop_column('incomes', 'date')
    op.drop_column('incomes', 'amount')
    op.drop_column('incomes', 'source')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_user_id_fkey'), 'expenses', 'users', ['user_id'], ['id'])
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'description')
    op.drop_column('expenses', 'amount')
    op.drop_column('expenses', 'category')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(op.f('budgets_user_id_fkey'), 'budgets', 'users', ['user_id'], ['id'])
    op.drop_column('budgets', 'monthly_limit')
    op.drop_column('budgets', 'category')
    # ### end Alembic commands ###
