"""add expense fields

Revision ID: d0a87bc2bd46
Revises: b606d521e2a9
Create Date: 2026-08-03 20:29:28.234093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a87bc2bd46'
down_revision: Union[str, Sequence[str], None] = 'b606d521e2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###
